services:
  - type: web
    name: brain-tumor-detection
    env: python
    buildCommand: |
      pip install -r requirements.txt
      pip install -e .
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
    plan: free
    disk:
      name: brain-tumor-data
      mountPath: /var/brain-tumor-data
      sizeGB: 1
